
```{r}
#' @title plot_xts
#' @description Plots time series from xts
#' @param x xts

plot_xts <- function(x, ...){
  x %>%
    as.data.frame() %>%
    tibble::rownames_to_column("date") %>%
    mutate(date = as.Date(date)) %>%
    gather(key, value, -date) %>%
    ggplot(aes(x = date, y = value, color = key)) +
    geom_line() +
    labs(x = "", y = "", color = "", ...)
}
```

```{r}
#' @title plotly_xts
#' @description Plots time series from xts
#' @param x xts

plotly_xts <- function(x, ...){
  x %<>%
    as.data.frame() %>%
    tibble::rownames_to_column("date") %>%
    mutate(date = as.Date(date)) %>%
    gather(key, value, -date)

  p <- x %>%
    plot_ly(x = ~date,
            y = ~value,
            color = ~key, ...) %>%
    add_lines()

  p
}
```

```{r}
#' @title get_prices_yahoo
#' @description Builds an xts containing time series downloaded from Yahoo! Finance.
#' @param yahoo_id character array containining yahoo ids.
#' @param from start date. Retrieve data no earlier than this date. (2007-01-01).
#' @param to end date. (Sys.Date())
#' @param column indicating which column should be returned: "Open", "High", "Low", "Close", "Volume", ("Adjusted")
#' @param ... additional parameters
#' @param periodicity periodicity of data to query and return. Must be one of "daily", "weekly", "monthly", ("daily")

get_prices_yahoo <- function(
  yahoo_id,
  column = 'Adjusted',
  from = "2007-01-01",
  to = Sys.Date(),
  ...,
  periodicity = "daily"
) {
  series <- list()
  i <- 0

  for(id in yahoo_id) {
    col <- paste(toupper(id), '.', column, sep = '')

    ss <- getSymbols.yahoo(id, auto.assign = FALSE,
                           from = from, to = to,
                           periodicity = periodicity, ...)[, col]

    i <- i + 1
    series[[i]] <- ss
  }

  series <- do.call(cbind, series)
  series <- na.locf(series, na.rm = FALSE, fromLast = TRUE)
  series
}

```

```{r}
get_dlyChg_from_price <- function(
  price
) {
  # calculamos cambios relativos diarios
  dlyChg <- price / lag.xts(price)
  # por conveniencia asignamos 1's al primer renglon de `dlyChg`
  dlyChg[1, ] <- 1
  dlyChg
}
```

```{r}
get_cumRet_from_dlyChg <- function(
  dlyChg
) {
  cumRet <- xts(order.by=index(dlyChg))
  for (c in 1:ncol(dlyChg)) {
    dlyChg_col <- log(dlyChg[ ,c])
    dlyChg_col[is.na(dlyChg_col)] <- 0
    cumRet <- cbind(cumRet, exp(cumsum(dlyChg_col)))
  }
  cumRet
}
```


escribe una lógica secuencial para obtener valores de portafolios con múlti-
ples fechas de rebalanceo
```{r}
get_rebalance_t2 <- function(
  dlyChg_t2,
  portWeightOpen_t2,
  portValue_t1
) {
  portSumTerm_t2 <- dlyChg_t2 * portWeightOpen_t2
  portChg_t2 <- sum(portSumTerm_t2)

  portWeightClose_t2 <- portSumTerm_t2 / portChg_t2
  portValue_t2 <- portValue_t1 * portChg_t2

  list(portWeight = portWeightClose_t2,
       portValue = portValue_t2)
}

get_rebalance_ <- function(
  dlyChg,
  rebWeight
) {
  stopifnot(index(rebWeight)[1] == index(dlyChg)[1])

  dates <- as.character(index(dlyChg))
  reb_dates <- as.character(index(rebWeight))

  portWeightOpen <- list()
  portWeight <- list()
  portValue <- list()

  portWeight[[dates[1]]] <- as.numeric(rebWeight[dates[1]])
  portValue[[dates[1]]] <- 1.0

  for(i in 2:length(dates)) {
    if(dates[i-1] %in% reb_dates) {
      portWeightOpen[[dates[i]]] <- as.numeric(rebWeight[dates[i-1]])
    } else {
      portWeightOpen[[dates[i]]] <- portWeight[[dates[i-1]]]
    }
    reb <- get_rebalance_t2(as.numeric(dlyChg[dates[i]]),
                            portWeightOpen[[dates[i]]],
                            portValue[[dates[i-1]]])
    portWeight[[dates[i]]] <- reb$portWeight
    portValue[[dates[i]]] <- reb$portValue
  }
  portWeight <- do.call(rbind, portWeight)
  portValue <- do.call(rbind, portValue)
  portWeight <- xts(portWeight, order.by = index(dlyChg))
  portValue <- xts(portValue, order.by = index(dlyChg))
  names(portWeight) <- names(dlyChg)
  names(portValue) <- 'port'

  list(portWeight = portWeight,
       portValue = portValue)
}

# ÚLTIMA MODIFICACIÓN DE REBALANCE EN LAS CONTRIBUCIONES
get_rebalance <- function(
  dlyChg,
  rebWeight
) {
  rebalance <- get_rebalance_(dlyChg, rebWeight)

  portContrib <- list()
  for(c in 1:ncol(dlyChg)) {
    dlyChg_c <- dlyChg[, c]
    dlyChg_c$fix <- 1
    rebWeight_c <- rebWeight[, c]
    rebWeight_c$fix <- 1 - rebWeight_c[, 1]
    portContrib[[c]] <- get_rebalance_(dlyChg_c, rebWeight_c)$portValue
  }
  portContrib <- do.call(cbind, portContrib)
  names(portContrib) <- names(dlyChg)
  rebalance[['portContrib']] <- portContrib
  rebalance
}

```

